config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :payments, only: [:new, :create]
end

app/models/transaction.rb
class Transaction
  # Methods
  def self.amount_for_type(type)
    case type
    when 'subscription' then 997
    when 'deposit' then 2000
    when 'purchase' then 700
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Extensions
  include Stripe::Callbacks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Callbacks
  before_create :create_stripe_customer
  after_customer_updated! do |customer, event|
    user = User.where(stripe_customer_id: customer.id).first

    if customer.account_balance < 1000
      Notifications.low_balance(user).deliver
    end
  end

  # Methods
  def do_deposit_transaction(type, stripe_token)
    amount = Transaction.amount_for_type(type)
    coupon = UserCoupon.coupon_for_amount(amount)

    card = save_credit_card(stripe_token)
    if deposited = deposit(amount, card)
      subscribe if type == 'subscription'
      create_coupon(coupon) if coupon

      deposited
    end
  end

  def stripe_customer
    Stripe::Customer.retrieve(stripe_customer_id)
  end

  def deposit(amount, card)
    customer = stripe_customer

    Stripe::Charge.create(
      amount: amount,
      currency: 'usd',
      customer: customer.id,
      card: card.id,
      description: "Charge for #{email}"
    )

    customer.account_balance += amount
    customer.save
  rescue => e
    false
  end

  private

  def subscribe
    stripe_customer.subscriptions.create(plan: 'monthly')
  end

  def create_coupon(coupon)
    customer = stripe_customer
    already_has_off3_coupon = customer.discount && customer.discount.any? { |type, co| type == :coupon && co.id == 'off3' }

    return true if coupon == 'off3' && already_has_off3_coupon

    customer.coupon = coupon
    customer.save
  end

  def create_stripe_customer
    customer = Stripe::Customer.create(email: email, account_balance: 0)
    self.stripe_customer_id = customer.id
  end

  def save_credit_card(card_token)
    stripe_customer.cards.create(card: card_token)
  end
end

app/models/user_coupon.rb
class UserCoupon
  # Methods
  def self.coupon_for_amount(amount)
    case amount
    when 997 then 'off2'
    when 2000 then 'off3'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def create
    if stripe_token = params[:stripe_token]
      if current_user.do_deposit_transaction(params[:payment_type], stripe_token)
        flash[:notice] = 'Card charged successfully'
      else
        flash[:alert] = 'Some error happened while charging you, please double check your card details'
      end
    else
      flash[:alert] = 'You did not submit the form correctly'
    end

    redirect_to new_payment_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StripeDev</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stripe_javascript_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= alert %>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/notifications/inactive_user.html.erb
<%= @message %>

app/views/notifications/low_balance.html.erb
<h1>Low balance</h1>

<p>
  <%= @message %>
</p>

app/views/payments/new.html.erb
<%= form_tag payments_path, id: 'card-details' do %>
  <div class="payment-errors"></div>

  <div>
    <label for="card-number">Card Number:</label>
    <input id="card-number" type="text" data-stripe="number" />
  </div>

  <div>
    <label for="card-exp-month">Card Expiry Month:</label>
    <input id="card-exp-month" type="text" data-stripe="exp_month" />
  </div>

  <div>
    <label for="card-exp-year">Card Expiry Year:</label>
    <input id="card-exp-year" type="text" data-stripe="exp_year" />
  </div>

  <div>
    <label for="card-cvc">CVC:</label>
    <input id="card-cvc" type="text" data-stripe="cvc" />
  </div>

  <div>
    <label for="payment-type">Payment Type:</label>
    <select id="payment-type" name="payment_type">
      <option value="deposit">$20 Deposit</option>
      <option value="subscription">Monthly subscription, $9.97</option>
    </select>
  </div>

  <div>
    <input type="submit" value="Pay Now" />
  </div>
<% end %>